### PR TITLE
add 'provides' to resource as required by chef v16

### PR DESCRIPTION
**Pull request by adamthiede**
https://docs.chef.io/release_notes_client/#breaking-change-in-resources
This would enable the cookbook to be used with chef-client version 16.

### CODE REVIEW

**Comment by bdwyertech** [comment]
Thanks!  I'm OOO for a bit but I'll try and get a release cut soon.

**Comment by adamthiede** [comment]
Wow, awesome! Thanks for the super quick response. I eagerly await the release.

**Comment by adamthiede** [comment]
Hi there, not to bug you, but just a friendly reminder. Any chance this is going up to supermarket any time soon? Take the time you need of course.

**Comment by bdwyertech** [comment]
Done

**Pull request merged**
